##
# Description: kubernetes部署文件，不同项目只用修改 distribution 替换为项目名
# @Date: 2019-04-23 16:14
# @Author: jim
##
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: order
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: order.jq.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: order
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: order
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        tail_files: true
        fields:
          ip: '${POD_IP}'
        paths:
          - /logs/*.log
        json.keys_under_root: true
        json.overwrite_keys: true
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    setup.template:
      name: "order"
      pattern: "order-*"
      overwrite: true
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      index: "order-%{+yyyy.MM}"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      imagePullSecrets:
        - name: harbor
      initContainers:
        - image: harbor.jq.cn/library/skywalking-sidecar:6.5.0
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: ['sh']
          args: ['-c','mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent']
          volumeMounts:
            - mountPath: /skywalking/agent
              name: sw-agent
        - name: arthas-sidecar
          image: hengyunabc/arthas:3.1.7-no-jdk
          imagePullPolicy: IfNotPresent
          command: ['sh']
          args: ['-c','mkdir -p /arthas && cp -r /opt/arthas/* /arthas']
          volumeMounts:
            - mountPath: /arthas
              name: arthas
      containers:
        - name: order
          imagePullPolicy: IfNotPresent
          image: harbor.jq.cn/library/order:19
#          resources:
#            limits:
#              cpu: 0.3
#              memory: 1000Mi
          ports:
            - containerPort: 8080
          env:
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: '192.168.123.10:11800'
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: AGENT_OPTS
              value: '-javaagent:/usr/skywalking/agent/skywalking-agent.jar'
            - name: JAVA_OPTS
              value: >-
                -Xms1024m
                -Xmx1024m
                -XX:NewRatio=4
                -XX:MetaspaceSize=256M
                -XX:MaxMetaspaceSize=256M
                -XX:+DisableExplicitGC
                -XX:+UseConcMarkSweepGC
                -XX:+CMSParallelInitialMarkEnabled
                -XX:+CMSParallelRemarkEnabled
                -XX:+UseFastAccessorMethods
                -XX:+UseCMSInitiatingOccupancyOnly
                -XX:CMSInitiatingOccupancyFraction=80
                -XX:+HeapDumpOnOutOfMemoryError
                -Dfile.encoding=UTF-8
                -Duser.timezone=Asia/Shanghai
                -Djava.security.egd=file:/dev/./urandom
                -Dspring.profiles.active=dev
                -Dspring.cloud.nacos.config.server-addr=192.168.123.176:8848
                -Dspring.cloud.nacos.config.namespace=15e9b66d-d9f0-45db-a992-703d634cd2d8
                -Dspring.cloud.nacos.discovery.namespace=15e9b66d-d9f0-45db-a992-703d634cd2d8
          volumeMounts:
            - name: app-logs
              mountPath: /logs
            - name: sw-agent
              mountPath: /usr/skywalking/agent
            - name: arthas
              mountPath: /opt/arthas
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: sw-agent
          emptyDir: {}
        - name: arthas
          emptyDir: {}
        - name: config
          configMap:
            defaultMode: 0600
            name: order-filebeat-config