##
# Description: kubernetes部署文件，不同项目只用修改 distribution 替换为项目名
# @Date: 2019-04-23 16:14
# @Author: jim
##
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: order
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
  - host: order.jq.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: order
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: order
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        tail_files: true
        fields:
          ip: '${POD_IP}'
        paths:
          - /logs/*.log
        json.keys_under_root: true
        json.overwrite_keys: true
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    setup.template:
      name: "order"
      pattern: "order-*"
      overwrite: true
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      index: "order-%{+yyyy.MM}"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: order
          imagePullPolicy: IfNotPresent
          image: harbor.jq.cn/library/order:62
#          resources:
#            limits:
#              cpu: 0.3
#              memory: 1000Mi
#          livenessProbe:
#            failureThreshold: 8
#            httpGet:
#              path: /k8s/health
#              port: 8080
#              httpHeaders:
#                - name: X-Custom-Header
#                  value: jim
#            initialDelaySeconds: 60
#            timeoutSeconds: 3
#            periodSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: JAVA_OPTS
              value: >-
                -Xms4096m
                -Xmx4096m
                -XX:NewRatio=4
                -XX:MetaspaceSize=256M
                -XX:MaxMetaspaceSize=256M
                -XX:+DisableExplicitGC
                -XX:+UseConcMarkSweepGC
                -XX:+CMSParallelInitialMarkEnabled
                -XX:+CMSParallelRemarkEnabled
                -XX:+UseFastAccessorMethods
                -XX:+UseCMSInitiatingOccupancyOnly
                -XX:CMSInitiatingOccupancyFraction=80
                -XX:+HeapDumpOnOutOfMemoryError
                -Dfile.encoding=UTF-8
                -Duser.timezone=Asia/Shanghai
                -Djava.security.egd=file:/dev/./urandom
                -Dspring.profiles.active=dev
                -Dspring.cloud.nacos.config.server-addr=nacos:8848
                -Dspring.cloud.nacos.config.namespace=a1a8ab7b-7299-44b6-8e76-13e3db762eef
          volumeMounts:
            - name: app-logs
              mountPath: /logs
#            - name: apiclient
#              mountPath: /opt/wxcert
#        - name: filebeat
#          image: docker.elastic.co/beats/filebeat:6.7.0
#          imagePullPolicy: IfNotPresent
#          args: [
#            "-c", "/etc/filebeat.yml",
#            "-e",
#          ]
#          env:
#            - name: POD_IP
#              valueFrom:
#                fieldRef:
#                  apiVersion: v1
#                  fieldPath: status.podIP
#            - name: ELASTICSEARCH_HOST
#              value: "elasticsearch-client.log"
#            - name: ELASTICSEARCH_PORT
#              value: "9200"
#          securityContext:
#            runAsUser: 0
#            privileged: true
#          volumeMounts:
#            - name: config
#              mountPath: /etc/filebeat.yml
#              subPath: filebeat.yml
#              readOnly: true
#            - name: app-logs
#              mountPath: /logs
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: config
          configMap:
            defaultMode: 0600
            name: order-filebeat-config
#        - name: apiclient
#          secret:
#            defaultMode: 420
#            secretName: apiclient